_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": darwin-arm64
